### ISSUE TITLE
[Request] Discord Server / Forum for more open discussion

### ISSUE THREAD

**Issue by James-P-Bennett** [lehjr/MachineMusePowersuits#100]
**Is your feature request related to a problem? Please describe.**
There's a need for a dedicated space where users can freely exchange ideas, provide feedback, and engage in constructive conversations regarding the mod.

**Describe the solution you'd like**
I propose creating a Discord server or similar forum platform specifically tailored for discussions about the mod.

**Describe alternatives you've considered**
Alternative solutions include expanding the existing Issues tab to accommodate more open discussions or creating dedicated threads regarding minor questions such as mod usage in relation to gameplay.

**Additional context**
Establishing a dedicated Discord server or forum would not only facilitate better communication among community members but also provide a centralized hub for gathering feedback, troubleshooting, and fostering a sense of community around the mod.

**Comment by lehjr** [comment]
Not only is there already a discord server setup but there is a discussion tab here at the top of the page.

**Comment by James-P-Bennett** [comment]
> Not only is there already a discord server setup but there is a discussion tab here at the top of the page.

Would you mind pointing me to the discord server? I'm having trouble finding the invite link

**Comment by lehjr** [comment]
https://discord.gg/Dkr5fDjN

**Comment by lehjr** [comment]
Not much going on there but it exists

**Comment by James-P-Bennett** [comment]
> Not much going on there but it exists

Thanks!
Perhaps you could consider placing the link on the main pages that way idiots like myself could locate it easier? Might help make the server a little more active :)

**Comment by kmecpp** [comment]
@lehjr Invite link doesn't work anymore. Is there still a Discord? Would be helpful if it was linked on the project Curse/Modrinth packages and in README

**Comment by lehjr** [comment]
https://discord.gg/Cfsa2sD6
Again though, not much going on there because I'm the only developer and my time is limited.
