### ISSUE TITLE
Modular power suit dont work with IC2 Classic

### ISSUE THREAD

**Issue by RedneTwo** [lehjr/MachineMusePowersuits#102]
**Version info**
Java version: 17
Minecraft Forge version: 1.19.2 - forge 43.3.9

**Describe the bug**
The armor dont show when put in your armor slot

**To Reproduce**
1. Go to install IC2 Classic and Modular Powersuit
2. Equip the armor from modular
3. See error

**Expected behavior**

**Mod list**
Including versions, provided by crash report if game crashed:
IC2 Classic "i test in all versions"
Modular Powersuit "i test in all versions"
Numina "i test in all versions"

**Screenshots**
![image](https://github.com/lehjr/MachineMusePowersuits/assets/72399593/1391926d-4a94-47dc-9b31-15631f385256)
![image](https://github.com/lehjr/MachineMusePowersuits/assets/72399593/336982a6-dac2-419a-a463-f8919656c1ee)

**Comment by RedneTwo** [comment]
I will pay if it is necessary for this mod to advance, to solve this error

**Comment by RedneTwo** [comment]
Tell me if there is any information missing

**Comment by lehjr** [comment]
Unfortunately this is not going to be something I can just say "oh it's this" and come up with a work around. The most likely cause is one of the mixins they use which causes ModelEvent.RegisterAdditional to simply not even fire. Figuring out which one, and figuring out a work around just isn't with the scope of available time I have.

**Comment by RedneTwo** [comment]
very sad

**Comment by Speiger** [comment]
@lehjr the info i can provide is the following.
Most of our mixins that ic2classic has are just accessor mixins because i want to avoid to use ATS (my own bias, i am working on it)
And those who aren't accessors are not even close to related to rendering itself.

But if there is anything I can fix let me know.

**Comment by lehjr** [comment]
Should be fixed in the latest build.

**Comment by RedneTwo** [comment]
i will test now
