### ISSUE TITLE
How can i use Forge: 43.2.8 and Java: 1.19.2 with the modular powersuits

### ISSUE THREAD

**Issue by FreeGobbys** [lehjr/MachineMusePowersuits#103]
Java version: 1.19.2
Minecraft Forge version: 43.2.8

I cant find any versions to use this mod with forge 43.2.8 only current verions
i have a server with friends on 1.19.2 with the essentials forge launcher but the forge installed is 43.2.8 is there any versions of machinemuse's modular powersuits  and numina that work on 43.2.8 with 1.19.2

**Comment by lehjr** [comment]
OK, so what's the issue? The mod isn't locked into a specific forge release version, just a Minecraft version.

**Comment by lehjr** [comment]
> OK, so what's the issue? The mod isn't locked into a specific forge release version, just a Minecraft version.

Yeah, so that's not entirely true. The mod info file does specify a version range. Fixed in build 12
