### ISSUE TITLE
Modular Powersuits models not showing up when equipped (1.12.2).

### ISSUE THREAD

**Issue by EntityIridescent** [lehjr/MachineMusePowersuits#21]
Modular powersuits do not have models, and appear on the player as if they did not have a set of armor on. The only piece that has a model is the Power Fist. I have checked in the cosmetics tab of the Tinker Table, and even with the MPS models enabled, nothing is displayed. Every mod on the following list is the latest version. 
The Forge Version is also the latest for 1.12.2 [.2855]. 

Modlist:
Just Enough Items (JEI) (by mezz)
Enchantment Descriptions (by DarkhaxDev)
ConnectedTexturesMod (by tterrag1098)
Thermal Dynamics (by TeamCoFH)
MovingWorld (by darkevilmac)
Chameleon (by Texelsaur)
Roguelike Dungeons -- Fnar's Edition (by FnarDotTv)
Charm (by svenhjol)
Tails (by Forge_User_78407710)
Aether: Lost Content (by ModdingLegacy)
BiblioCraft (by Nuchaz)
Davincis Vessels (by darkevilmac)
AI Improvements (by QueenOfMissiles)
Clarity (by EpicSquid315)
Fossils and Archeology Revival (by _ForgeUser18449974)
LLibrary (by _ForgeUser11902522)
BiomeTweaker (by superckl)
spark (by Iucko)
Aether Continuation (by XaeronTheProtogen)
Future MC (by thedarkcolour)
Antique Atlas (by Hunternif)
FastFurnace (by Shadows_of_Fire)
Flux Networks (by sonar_sonic)
Improved Backpacks (by DreenDexTwitch)
Chisel (by tterrag1098)
Foam​Fix (by asiekierka)
Tinkers Construct (by mDiyo)
Crafting Tweaks (by BlayTheNinth)
Immersive Petroleum (by Flaxbeard)
WorldEdit (by sk89q)
Patchouli (by Vazkii)
Mantle (by mDiyo)
CraftTweaker (by Jaredlll08)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Colytra (Forge) (by TheIllusiveC4)
Redstone Flux (by TeamCoFH)
Techguns (by pWn3d_1337)
IvToolkit (by Ivorforce)
Recurrent Complex (by Ivorforce)
CodeChicken Lib 1.8.+ (by covers1624)
Thermal Foundation (by TeamCoFH)
Astral Sorcery (by HellFirePvP)
The Midnight (by cipher_zero_x)
CoFH Core (by TeamCoFH)
Cooking for Blockheads (by BlayTheNinth)
Thermal Expansion (by TeamCoFH)
Quark (by Vazkii)
Rustic (by cadaverous_queen)
Aqua Acrobatics (by Fuzs_)
Cosmetic Armor Reworked (by LainMI)
CoFH World (by TeamCoFH)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Stargate Network (by Almura_Dockter)
Touhou Little Maid (by TartaricAcid)
Genetics Reborn (by TheUnderTaker11_)
Clumps (by Jaredlll08)
Baubles (by Azanor13)
The Twilight Forest (by Benimatic)
Corail Tombstone (by Corail_31)
New Textures (by mirosmir)
New TARDIS Mod (by spectre0987)
Comforts (Forge) (by TheIllusiveC4)
AutoRegLib (by Vazkii)
BetterFps (by Guichaguri)
FastWorkbench (by Shadows_of_Fire)
Mouse Tweaks (by YaLTeR)
Pam's HarvestCraft (by pamharvestcraft)
Phosphor (Forge) (by jellysquid3)
LibVulpes (by zmaster587)
Advanced Rocketry (by zmaster587)
Shadowfacts' Forgelin (by ShadowfactsDev)
MineTweaker RecipeMaker (by DoubleDoorDev)
Numina (by machinemuse)
Controlling (by Jaredlll08)
Modular Powersuits (by machinemuse)
Abyssal Depths (by Chumbanotz)
Tinkers' Tool Leveling (by bonusboni)
More Overlays (by FeldiM245)
Placebo (by Shadows_of_Fire)
Electroblob's Wizardry (by Electroblob)

**Comment by lehjr** [comment]
1.12.2 is no longer supported due to the development environment being broken.
