### ISSUE TITLE
textures for powerfist and the gui for the tinker table is messed up

### ISSUE THREAD

**Issue by DarklyNightly** [lehjr/MachineMusePowersuits#24]
<img width="1280" alt="Screen Shot 2021-08-26 at 8 51 44 PM" src="https://user-images.githubusercontent.com/75499681/131054408-f08ae205-d6ea-4809-86a1-526530ffa0a1.png">
<img width="1280" alt="Screen Shot 2021-08-26 at 8 51 27 PM" src="https://user-images.githubusercontent.com/75499681/131054411-45ce593d-1e09-4bdb-9729-bc4ca75279ce.png">

Modpack i am using: https://www.curseforge.com/minecraft/modpacks/modded-oneblock-skyblock

**Comment by Cyberian10** [comment]
Can confirm this happens on non-modpack instances of this mod.

**Comment by ProsperCraft** [comment]
I can confirm this is happening in TownCraft TWO for 1.16.5

ModularPowersuits-1.16.5-2.1.17
Numina-1.16.5-2.1.14
forge-1.16.5-36.2.19

**Comment by asenright** [comment]
Am also having this issue, specifically the green channel is not being correctly applied

**Comment by lehjr** [comment]
> 

an actual screenshot would be helpful

**Comment by lehjr** [comment]
> I can confirm this is happening in TownCraft TWO for 1.16.5
> 
> ModularPowersuits-1.16.5-2.1.17 Numina-1.16.5-2.1.14 forge-1.16.5-36.2.19

a more recent screenshot would be helpful

**Comment by ProsperCraft** [comment]
![image](https://user-images.githubusercontent.com/4427684/147313997-38470d3f-8e47-4f54-9a7d-591fc7d59392.png)
Still an issue after the update - 
Numina-1.16.5-2.1.16
ModularPowersuits-1.16.5-2.1.18
![image](https://user-images.githubusercontent.com/4427684/147314106-50853502-a98b-40be-973a-955764404801.png)

**Comment by lehjr** [comment]
> ![image](https://user-images.githubusercontent.com/4427684/147313997-38470d3f-8e47-4f54-9a7d-591fc7d59392.png)
> Still an issue after the update -
> Numina-1.16.5-2.1.16
> ModularPowersuits-1.16.5-2.1.18
> ![image](https://user-images.githubusercontent.com/4427684/147314106-50853502-a98b-40be-973a-955764404801.png)

Logs would help.

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/b615ea9426cfb790c27e470be7d19490
https://github.com/TwistedGate/ImmersivePetroleum/files/7771799/debug.zip

**Comment by lehjr** [comment]
The issue is not with this mod but with an unknown incompatibility with another mod in the modpack. If anyone wants to take the time to narrow it down, then I will be more to look into this. However, I am not going to do this.

**Comment by DarklyNightly** [comment]
> The issue is not with this mod but with an unknown incompatibility with another mod in the modpack. If anyone wants to take the time to narrow it down, then I will be more than happy to look into this. However, I am not going to do this as it is too time consuming and troubleshooting compatibility issues in modpacks would leave no time for anything else.

could it be optifine?

**Comment by lehjr** [comment]
nope.

**Comment by lehjr** [comment]
> > The issue is not with this mod but with an unknown incompatibility with another mod in the modpack. If anyone wants to take the time to narrow it down, then I will be more than happy to look into this. However, I am not going to do this as it is too time consuming and troubleshooting compatibility issues in modpacks would leave no time for anything else.
> 
> could it be optifine?

No, it's Smooth Boot and no fix is possible.
