### ISSUE TITLE
[1.16.5] The flight control module makes you move without player input

### ISSUE THREAD

**Issue by Frankaos333** [lehjr/MachineMusePowersuits#34]
(Mod version 2.1.15, Forge version 36.2.8, also observed in mod version 2.1.17), when activating the flight control module in combination with the jet boots, jet pack or both, the vertical thrust is reduced, making you raise a bit slower, furthermore, moving along the z axis (both parallel to it and diagonally with a component along it) when the thrusters are active applies a strong acceleration along the z axis in the direction you're moving which continues after you've released the movement keys, finally, when the y look ratio is set above zero, moving while looking up won't actually make you go straight up but it will also make you move forward.

**Comment by lehjr** [comment]
this will finally be fixed in beta 9.

**Comment by lehjr** [comment]
Fixed in beta 9
