### ISSUE TITLE
Item missing texture and lang key

### ISSUE THREAD

**Issue by Sunekaer** [lehjr/MachineMusePowersuits#36]
![image](https://user-images.githubusercontent.com/18720460/142436990-8e320415-1d60-42c6-b260-65f92a9dacbc.png)

**Comment by ProsperCraft** [comment]
I can confirm that this is a problem in 
Numina-1.16.5-2.1.14
ModularPowersuits-1.16.5-2.1.17

**Comment by lehjr** [comment]
yeah, that's an item that I just added last minute to do some testing with. I wasn't sure if it was going to work out, but it does seem to be working. I'll be fixing that a bit later on.

**Comment by lehjr** [comment]
Issue was fixed awhile ago
