### ISSUE TITLE
[1.16.5] Server lockup due to Powerfist entities - lux capacitors, railgun

### ISSUE THREAD

**Issue by ProsperCraft** [lehjr/MachineMusePowersuits#37]
![image](https://user-images.githubusercontent.com/4427684/143374135-aeeac266-337a-4c0b-abc2-5b535df61965.png)

Numina-1.16.5-2.1.14
ModularPowersuits-1.16.5-2.1.17

Modpack TownCraft TWO for 1.16.5

I had placed about 100 caps in a giant cavern about 5 minutes prior to the server tanking.

**Comment by ProsperCraft** [comment]
Happened again - 
![image](https://user-images.githubusercontent.com/4427684/143530698-e860a505-9ca4-4125-b865-0aa78e747fa4.png)

**Comment by ProsperCraft** [comment]
Happened again, full lockup, players don't get kicked, This time it was due to a railgun entity not lux caps.
![image](https://user-images.githubusercontent.com/4427684/143594718-11d223f8-6465-4203-b02c-88ab472ffd21.png)

**Comment by ProsperCraft** [comment]
Another one - right when shooting a lux cap- 
![image](https://user-images.githubusercontent.com/4427684/143666875-6cd1497f-ba4c-4513-a2f4-14f57d122645.png)

**Comment by lehjr** [comment]
an actual log would be helpful

**Comment by lehjr** [comment]
also, just naming a modpack isn't helpful. There's no way that I can spend my free time looking up modpacks, then sifting through those modpacks looking for any offending mod that might cause the issue on your end. If I did that, development of this mod would no longer be possible due to time constraints.

**Comment by lehjr** [comment]
Still haven't seen any useful information regarding this. So I can only assume this issue is no longer valid.
