### ISSUE TITLE
Problem with cooling in FTB Revelation

### ISSUE THREAD

**Issue by lauma** [lehjr/MachineMusePowersuits#38]
Hi! I am using Modular Powersuits in FTB Revelation modpack and I am struggling with overheating, and after all the Googling I'm still not sure, if it is a bug or I am doing things plain wrong. 

Internet suggests heat sinks and cooling systems. 
- Heat sink recipe is not available in tinker table for none of the porwersuit parts (I have all five - armor and tool) - does that mean it is obsolete? I checked, server runs verson 1.12.2-1.0.46
- If I install cooling system, I can stand in water how long I want, even in ocean, armor keeps sucking in the water, but cooling liquid bar never fills. If I install advanced cooling system, the same happens with non-water liquids, which is particularly confusing, if I fall in some exotic liquid I was trying to collect, as it gets destroyed. Do I need some kind of tank? I checked tinker table, didn't see any tanks for any part.

Server I'm playing on, is not mine, thus, I don't see config files, and it has also one or two mods outside the FTB Revelations, but if I had precise idea, I could suggest improvements or reconfigurations.

Huge thanks for any advice.

**Comment by ProsperCraft** [comment]
Turn down your overclocking?

**Comment by lehjr** [comment]
1.12.2 hasn't been supported in quite awhile due to the development environment being broken.

**Comment by lauma** [comment]
Overclocking didn't help, I made the simplest possible armor (only chestplate with just battery and cooling), and problem is still the same.  Ok, if it is obsolete then probably nothing can be done I guess. Thanks.

**Comment by MrRedstoneA1** [comment]
don't use the regular cooling module. It doesn't work properly. Only install advanced cooling system and remember to adjust the cooling power. Heatsinks are no longer a thing.
