### ISSUE TITLE
Casting Errors

### ISSUE THREAD

**Issue by C4J3** [lehjr/MachineMusePowersuits#42]
Issue with Numinia installed causing errors with other mods. [TFar's Dank Storage ](https://github.com/Tfarcenim/Dank-Storage/issues/115) has an issue with casting air to a Dank which we suspect is Numinia as removing it solves the issue. 

~~I've also seen errors like [this](https://pastebin.com/raw/FwXk41c1) which reference Numinia explicitly at the start.~~ (This seems to be to do with `handleBreakSpeed` which I guess is to do with mining speed while the first lot is `handleBreakSpeed` and icon changing. (I assume when stuff in the hotbar is dropped.))

**Comment by lehjr** [comment]
That's not on my end as that was fixed on this end months ago:
https://github.com/lehjr/Numina/blob/1.16.5/src/main/java/com/github/lehjr/numina/util/client/render/RenderGameOverlayEventHandler.java#L68-L69

**Comment by lehjr** [comment]
also, your log regarding the breakspeed casting is using an obsolete version
