### ISSUE TITLE
Tinker Table Not Showing Modules

### ISSUE THREAD

**Issue by AdamBundschuh** [lehjr/MachineMusePowersuits#43]
Modular Powersuits is part of the FTB Ultimate Anniversary pack, and is listed as using "ModularPowersuits-1.16.5-2.1.17.jar" for reference.

When wearing a full suit of power armor, and accessing the tinker table, no modules show up in any of the tabs (besides the two vanilla head pieces). Screenshots:

![147440841-6a5aaff4-24dc-45b7-b6f6-0e2d32e47abc](https://user-images.githubusercontent.com/82165558/147853905-41354ba8-2d72-4910-8712-f4b51da3268e.jpg)

![147440842-774a081b-3061-4c0e-bd96-55a86a064d11](https://user-images.githubusercontent.com/82165558/147853907-4ab625b5-b4eb-42ef-ac5f-919ec255c4e8.jpg)

**Comment by lehjr** [comment]
That's an outdated version that was already fixed weeks ago when that GUI was overhauled. Aside from that GUI being trash, only unlocked recipes would show.
