### ISSUE TITLE
Unable to use the suit when battery level is below 800K

### ISSUE THREAD

**Issue by CrossVas** [lehjr/MachineMusePowersuits#46]
Version: [ModularPowersuits-1.16.5-RC-1](https://www.curseforge.com/minecraft/mc-mods/modular-powersuits/files/3677441)

Crafting Basic Battery gives you extra 800k energy, okay, not a big deal, free energy is always good...
Install Kinetic generator, start moving and you'll see that the energy is going up, cool.
But when you install any modules that require energy (I used sprint assist) start using/moving, the energy goes below 800k and, boom!!! it is shown as 0, although the Tinker table is showing the correct amount  (<800k)
Then when you are below 800k it is not possible to recharge it anymore using Kinetic generator, the energy is still going down. 

Now, another strange moment is when you cheat batteries from JEI with 0 energy it is not possible to charge this battery. I tried using solar to give it a little amount of energy so it could run, but nothing, it is impossible to recharge.

Also tried other batteries, same result.

First, craft a basic battery: 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/25727222/158008962-19ce19e5-57b5-4096-8452-89a015dd6787.png">
Install the module -> we have 800k energy, cool
![image](https://user-images.githubusercontent.com/25727222/158009031-5371e562-81de-40d2-8495-81dc1c5966db.png)
Getting Kinetic Generator on board, starting moving: 
![image](https://user-images.githubusercontent.com/25727222/158010104-cfa9f5ce-84fd-4995-ad02-44db6723b866.png)

Install any module that uses energy and take away Kinetic Generator (I used Sprint Assist with the config below)
<img width="782" alt="image" src="https://user-images.githubusercontent.com/25727222/158009099-17836a3e-3421-4cad-aedf-05ba2fd96b8b.png">
Move!!! And yeet -> we have 0 energy... instantly!
![image](https://user-images.githubusercontent.com/25727222/158009150-a68f0633-b72c-495b-b536-29636ce9c96a.png)
Go back, see the Tinker Table showing the current amount
<img width="791" alt="image" src="https://user-images.githubusercontent.com/25727222/158009801-338f5d79-9b20-4510-8994-8424e693b017.png">

**Comment by lehjr** [comment]
Found the issue, should have a fix up in a couple days.

**Comment by CrossVas** [comment]
Okay, cool. Thank you. :+1:

**Comment by CrossVas** [comment]
Seems to be fixed in [ModularPowersuits-1.16.5-2.2.23.jar](https://www.curseforge.com/minecraft/mc-mods/modular-powersuits/files/3708532)
