### ISSUE TITLE
[1.16.4] Alpha 2 - Testing

### ISSUE THREAD

**Issue by CrossVas** [lehjr/MachineMusePowersuits#5]
# Modules:
## General
- Armor plating: leather missing recipe, energy shield not working at all, salvage problems;
- Transparent armor: not working/not vanishing;
## Helmet
- Solar Generator: working fine;
- High Efficiency Solar generator: working fine;
- Auto Feeder: missing recipe, working fine; 
- Water Electrolyzer: missing recipe, working fine, but not taking energy;
- Flight Control, missing recipe, see #4; 
- Binocular: working fine;
- Night Vision: working fine; 
## Chest
- Kinetic Generator: missing recipe, working fine; 
- Thermal Generator: not installable; 
- Cooling System: missing recipe, not sure if heat logic is working at all; 
- Fluid Tank: missing recipe, working fine (?) [it is taking water sources]; 
- Mob Repulsor: missing recipe, working fine, but not taking energy; 
- Glider: missing recipe, not working;
- Jetpack: missing recipe, working fine, but not taking energy; 
- Parachute: missing recipe, not working; 
- Active Camouflage: missing recipe, working fine;
- Magnet: missing recipe, working fine, but not taking energy;
## Leggings
- Uphill Step Asist: missing recipe, working fine; 
- Shock Absorber: missing recipe, working, but not taking energy;
- Sprint Asist: missing recipe, working fine, but not taking energy;
- Swim Boost: missing recipe, working fine, but not taking energy;
## Boots
- Jet Boots: missing recipe, working fine, but not taking energy; 
- Jump Asist: missing recipe, working fine, but not taking energy;
## Fist
- AoE Module: working fine; 
- Aqua Afinity: missing recipe, working fine; 
- Silk/Fortune Module: missing recipes, not working; 
- Vein Miner: working fine; 
- Blink Drive: missing recipe, working fine; 
- Dimensional Tear Generator: not sure how it is supposed to work; 
- Axe, Diamond Drill Upgrade, Flint and Steel, Rototiller, Leaf Blower - working fine, but not taking energy; 
- Lux capacitor: working fine, but not taking energy,r salvage problems; 
- Pickaxe, Shovel: working fine, but not taking energy; 
- Shears: not working; 
- Blade Launcher: working fine, but not taking energy; 
- Lightning Summoner, Melee Asist, Plasma Cannon, Railgun:  working fine;

**Comment by PrincessOfEvil** [comment]
Leather Armor: wrong condition (copypaste error)
Tinker Table: erroring recipe (wrong output)
