### ISSUE TITLE
[Request] Power Shield ( item ) 1.12.2

### ISSUE THREAD

**Issue by redfoxrommy** [lehjr/MachineMusePowersuits#51]
Have you consider adding power armer shield ver.

Blocking melee attacks / send back range attacks ( like ghast and blaze)
adds armor ( obvius ) 
costumaciable color and shapes 
solar panel that produce power
or ect

**Comment by lehjr** [comment]
No changes will be made to 1.12.2. It’s several years old now and the development environment is broken and unsupported.
