### ISSUE TITLE
[Request] Give Kinetic Generator the powah!

### ISSUE THREAD

**Issue by CrossVas** [lehjr/MachineMusePowersuits#55]
**Is your feature request related to a problem? Please describe.**
So, back in 1.12.2 and prior it was possible to generate sufficient amount of energy for modular armor to maintain its capacity and operability. Now even with Kinetic Generator installed it's impossible to fully maintain the charge while flying (which was possible before).

**Describe the solution you'd like**
The solution I would like to see is a config to allow Kinetic Generator to generate energy even from flying (if possible). It might seem to be OP, but that's why I suggest it as a config.

**Describe alternatives you've considered**
In order to keep up the charge I'm using Flux-Network Wireless charger which is a mid-game system and not a solution I'm satisfied about. I need to use it in every modpack I play only for one purpose.

**Comment by lehjr** [comment]
If it was generating power while flying then it was a bug. That said, the amount of power the kinetic generator generates is already configurable.

**Comment by CrossVas** [comment]
Indeed it is configurable, but the problem is that you have to move on the ground in order to generate power. My point was to make fly generation option configurable.

**Comment by lehjr** [comment]
That's exactly how it's supposed to work and the entire point of it.

**Comment by CrossVas** [comment]
Then it makes the entire armor set useless by being unable to recharge on its own. Let's say I'm flying far using only my jet + sprint assist on 150%. With full cap, how far could I go? The amount of blocks is ridiculous for this kind of armor set. It needs an autonomous source of power.

My next question is: what's the best source of power for this case? 
No ofense meant in any way.

**Comment by lehjr** [comment]
kinetic generator is literally to generate power by movement. And there really aren't any good ways to generate power for the mod. The main focus is armor, not power generation. As it stands I already get enough complaints for balance and everything being too overpowered.

**Comment by lehjr** [comment]
It makes it really difficult to even begin to have any kind of linear progression if all you want is unlimited power and whatever else from the beginning.

**Comment by lehjr** [comment]
so basically I should just try to please everyone? Every configuration option adds a level of complexity that's likely to break something, and usually ends up becoming a nightmare when porting. It's the Achilles heel of development of the mod.
