### ISSUE TITLE
1.16.5 Active modules constantly drain any energy items the player is holding

### ISSUE THREAD

**Issue by Raidobw2** [lehjr/MachineMusePowersuits#58]
**Version info**
Java version: 8u312
Minecraft Forge version: 36.2.26 on Minecraft 1.16.5

**Describe the bug**
If MPS and Numina are installed, as well as Refined Storage, energy items the player holds will be drained first if an active module needs energy

**To Reproduce**
1. Install `Numina-1.16.5-2.2.30.jar`, `ModularPowersuits-1.16.5-2.2.30.jar` and `refinedstorage-1.9.17.jar` on Forge 36.2.26
2. Load the game and get yourself the MPS chestplate with jetpack module, activate it by binding the key
3. Get any wireless terminal from RS
4. Fully charge the terminal and the chestplate
5. Don't hold the terminal in your hand and fly -- nothing exceptional happens
6. Hold the terminal in your hand and fly, it will be drained

**Expected behavior**
It doesn't make sense for it to drain items in the selected slot in the hotbar for energy, so the expected behavior is that it shouldn't

**Mod list**
See steps to reproduce
`Numina-1.16.5-2.2.30.jar`, `ModularPowersuits-1.16.5-2.2.30.jar` and `refinedstorage-1.9.17.jar`

**Log files**
N/A

**Screenshots**
See below for a demonstration with the mods stated above + a few others to add energy items such as Thermal and IF

https://user-images.githubusercontent.com/17010632/184264052-67a33b14-cb4d-4ef4-b3bd-fee3100b495e.mp4

**Additional context**
Removing Refined Storage "fixes" this. This may be caused by something in the Refined Storage integration, maybe in https://github.com/lehjr/MachineMusePowersuits/commit/3a247f92032f58a1d9226e2522d9e8bda890c447
Relaying this issue from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1256

**Comment by lehjr** [comment]
This has been an ongoing issue due to the inability to identify which items are intended for use as a power source and which ones aren't. The simplest and most reliable fix will be for me to just implement a whitelist. That said, I will take a look when I get a chance and see if there isn't something less obvious going on here.

**Comment by Raidobw2** [comment]
Alrighty, thank you in advance for looking into it!

**Comment by Raidobw2** [comment]
I can confirm build 31 fixed it :) thank you very much, I appreciate the fix!

https://user-images.githubusercontent.com/17010632/197329650-3060522d-e4c9-49af-808f-147b35c551a3.mp4

The issue is resolved so I will close it, have a good weekend!
