### ISSUE TITLE
please 1.19.2

### ISSUE THREAD

**Issue by Acat1234** [lehjr/MachineMusePowersuits#76]
please port to 1.19.2 and if possible make the energy shields have a model as a shield around the player and make it so the barrier blocks 100% of damage to make it a force field thank you 😺

**Comment by lehjr** [comment]
1.19.3 port is currently in testing. Once it's done I might backport to 1.19.2. No guarantees. As for the other part of the request, maybe, but that depends on time.

**Comment by Agent312** [comment]
Maybe additionally 1.18.2 ?

**Comment by lehjr** [comment]
> Maybe additionally 1.18.2 ?

Unfortunately the more versions of Minecraft I try to support at once, the worse the support will be.

**Comment by Agent312** [comment]
> > Maybe additionally 1.18.2 ?
> 
> Unfortunately the more versions of Minecraft I try to support at once, the worse the support will be.



Understandable

**Comment by Agent312** [comment]
> I said 1.19.2 not 1.18.2 so Agent312 this is not were to talk about it.


ok

**Comment by lehjr** [comment]
1.19.2 is now being worked on

**Comment by robit4** [comment]
yay

**Comment by lehjr** [comment]
first alpha should be up on curseforge and Modrinth tomorrow (July 26). Most of the major bugs  from porting from 1.19.3 have been fixed as far as I can tell from testing.

**Comment by lehjr** [comment]
alpha builds are up on both Cureseforge and Modrinth. Might be a couple more weeks for beta builds.

**Comment by kurtramone** [comment]
Wow, onde of my favourite mods is back, I'll be testing 1.19.2 once beta is out

**Comment by lehjr** [comment]
Probably won't be too long, maybe on the weekend. Currently Im working on cleaning up translations and streamlining the process of creating them when content is added or is changed.

**Comment by lehjr** [comment]
There have been some delays in releasing the first beta. However, things are looking up a bit: 
![2023-11-10_13 56 32](https://github.com/lehjr/MachineMusePowersuits/assets/1084367/d2ea5ca5-859c-4da6-9e11-07756fdd7288)

**Comment by kurtramone** [comment]
Nice, very cool, I'm excited about it!
