### ISSUE TITLE
I get this error message while trying to open mincraft

### ISSUE THREAD

**Issue by UsernameCody** [lehjr/MachineMusePowersuits#77]
On the latest version of MP i downloaded it and tried opening minecraft but keep getting this error.
i checked everything and disabled all my other mods but nothing happens it just keeps doing this error.
![Screenshot (939)](https://github.com/lehjr/MachineMusePowersuits/assets/126016738/ef92d248-1e06-46e4-860c-6694c0a67bfe)

**Comment by lehjr** [comment]
not enough information
