### ISSUE TITLE
Ticking error message when playing with the MPS

### ISSUE THREAD

**Issue by UsernameCody** [lehjr/MachineMusePowersuits#79]
ModularPowersuits-1.12.2-1.1.048.jar

When playing with the latest version of modular powersuits, when you apply modules to the suit and wear the armour
it crashes the game and gives an error message. i have tried many different modules and many different ways to use them
but it always crashes the game.

1.Install MPS and numina and add to the mods folder
2.open minecraft and create a new world
3.Obtain the modular powersuit and apply modules (parachute/jetpack seem to cause the most problems)
4.wear the armour and attempt to use it

Normally it should use the armour just fine and the modules should work but it just crashes and creates issues.
![Screenshot (944)](https://github.com/lehjr/MachineMusePowersuits/assets/126016738/43f68f0e-40bd-4e05-a1b9-407571615bd7)

**Comment by lehjr** [comment]
new build of Numina up on curseforge should fix that

**Comment by UsernameCody** [comment]
> new build of Numina up on curseforge should fix that

thanks it worked :)
