### ISSUE TITLE
Game crashes when equiping powersuit on 1.19.2

### ISSUE THREAD

**Issue by NazRethh** [lehjr/MachineMusePowersuits#81]
**Version info**
Java version: 1.19.2
Minecraft Forge version: 43.2.13

**Describe the bug**
Crashes the game and if u add it in a server it crashes it before even being online

**To Reproduce**

1, equip powersuit 

**Expected behavior**
to not crash lol

**Mod list**
Including versions, provided by crash report if game crashed: 

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
 game crash report https://pastebin.com/TFLzMMJW
 server crash report https://mclo.gs/RDhTC51

**Screenshots**

**Additional context**
![image](https://github.com/lehjr/MachineMusePowersuits/assets/141244605/7e3f531e-f79f-433f-b8eb-8205b133a5e0)
![image](https://github.com/lehjr/MachineMusePowersuits/assets/141244605/63a01e53-de80-4c28-875c-b9feecbbba4a)
![image](https://github.com/lehjr/MachineMusePowersuits/assets/141244605/d3de903f-b5b3-4f92-9b5f-98813671e1ce)
![image](https://github.com/lehjr/MachineMusePowersuits/assets/141244605/89dd2c55-99d8-4a68-b070-e722baad2cda)
 this are all the mods that i use

**Comment by lehjr** [comment]
testing a fix now, probably will be uploaded tomorrow

**Comment by lehjr** [comment]
"should" be fixed in latest build
