### ISSUE TITLE
[Request] AEAdditions and p455w0rd's wireless terminals support (1.12.2)

### ISSUE THREAD

**Issue by Kuzibaba** [lehjr/MachineMusePowersuits#85]
**Is your feature request related to a problem? Please describe.**
I want to merge my wireless terminals with my power tool
terminals i would like to be implemented:
wireless fluid terminal (aeadditions)
wireless gas terminal(aeadditions
wireless crafting terminal(p455word's wireless terminals)
wireless interface terminal(p455word's wireless terminals)
wireless pattern terminal(p455word's wireless terminals)
wireless ultimate terminal(p455word's wireless terminals)

**Describe the solution you'd like**
adding wireless terminal modules

**Additional context**
it would be perfect if you could merge all 5 into one ultimate terminal(fluid,gas,crafting,pattern,interface

**Comment by lehjr** [comment]
Unfortunately there’s only so much time 1 person can spend on development and my time would be better spent working on current version than trying to add features to an old version.

**Comment by Kuzibaba** [comment]
Oh, yeah thats right but i rgink it will be easy adding the aeadditions terminal because it is just extracells addon. I was going thru the code of the mod and i think if you just switch the mod ids from extracells to aeadditions it will be done. I tried to do it but the files were not editable

**Comment by lehjr** [comment]
Like I said, I have to prioritize my time. If I had unlimited time then that wouldn’t be an issue. However there are only so many hours in a day, and adding code to a version that has has largely been untouched for years isn’t a trivial matter. But if you feel it’s that easy, then by all means, go ahead.

**Comment by Kuzibaba** [comment]
Alright I will try to do it thanks for reviewing
