### ISSUE TITLE
Plasma cannon doing little damage

### ISSUE THREAD

**Issue by RealGrong** [lehjr/MachineMusePowersuits#89]
**Version info**
Java version:1.19.2
Minecraft Forge version:43.2.13

**Describe the bug**
the plasma cannon only does one damage when fully charged
**To Reproduce**

**Expected behavior**
I'd imagine it would do more damage
**Mod list**
Including versions, provided by crash report if game crashed:

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
Crash report (if issue caused game to crash):
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash):

**Screenshots**

**Additional context**

**Comment by lehjr** [comment]
Try turning it up?
