### ISSUE TITLE
Not Compatible with Industrial Foregoing

### ISSUE THREAD

**Issue by James-P-Bennett** [lehjr/MachineMusePowersuits#97]
**Version info**
Java version: 17.0.9 x64
Minecraft Forge version: 1.19.2-43.3.8

**Describe the bug**
Not Compatible with Industrial Foregoing.
When both mods are installed, the tinker table module inventory breaks and no longer renders, making the armor unusable.

**To Reproduce
Steps to reproduce the behavior:**

Install the MMMPS
Install Industrial Foregoing
Equip the default armor
Select "modules" tab in the tinker table
The game will briefly freeze as it prints the error log
The module inventory screen is missing in the GUI

**Expected behavior**
Should be able to see an inventory grid in the tinker table modules tab.

**Mod list
Including versions, provided by crash report if game crashed:**
ModularPowersuits-1.19.2-2.3.8
Numina-1.19.2-2.3.8
industrial-foregoing-1.19.2-3.3.2.3-8
titanium-1.19.2-3.7.3-27

**Smallest sub-list that still produces issue, if any exclusion testing was done:**
ModularPowersuits-1.19.2-2.3.8
Numina-1.19.2-2.3.8
industrial-foregoing-1.19.2-3.3.2.3-8
titanium-1.19.2-3.7.3-27
Please note JEI was installed in a later exclusion test, so you might see that in the logs. With or without the mod installed it produces the same outcome.

**Log files**
https://pastebin.com/1CTNrEC4

**Screenshots**
https://imgur.com/a/biI0I1l

**Comment by James-P-Bennett** [comment]
**Updated log file during true exclusion testing**
https://pastebin.com/UhePNw6z

**Comment by lehjr** [comment]
should be fixed in 1.19.2-2.3.9
