### ISSUE TITLE
1.19.2-2.3.9 MMMPS / Numina does not load on Forge 1.19.2-43.3.0

### ISSUE THREAD

**Issue by James-P-Bennett** [lehjr/MachineMusePowersuits#99]
**Version info**
Java version: 17.0.9
Minecraft Forge version: 1.19.2-43.3.0

**Describe the bug**
The mod doesn't load and the client crashes.

**To Reproduce**
1. Install a clean forge installation of 1.19.2-43.3.0
2. install 1.19.2-2.3.9 MMMPS / Numina mods
3. Launch the game

**Expected behavior**
The game should load without issue.

**Mod list**
Mods:
  [✔] ModularPowersuits-1.19.2-2.3.9
  [✔] Numina-1.19.2-2.3.9

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
https://pastebin.com/QJLBsXTP

**Screenshots**

**Additional context**

**Comment by James-P-Bennett** [comment]
Likely forge isn't compatible with the mixin version

**Comment by lehjr** [comment]
Not sure what the issue is. Downgraded the Forge version and built against that and it seems to be working fine now. New builds are available on Modrinth now, and waiting on approval on curseforge.

**Comment by James-P-Bennett** [comment]
I can appreciate the prompt resolution! I'll give it a shot and report back shortly

**Comment by James-P-Bennett** [comment]
Works great, thanks again!
